/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination;

import java.awt.Dimension;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class Exam_question extends javax.swing.JFrame {
DbConnection db;
    /**
     * Creates new form Examination
     */
    public Exam_question() throws ClassNotFoundException {
        initComponents();
        
         db = new DbConnection() ;
         setQuestion();
        
    }
    int i = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String set = random();
    static ArrayList<Integer> q_no = new ArrayList <Integer>();
    String ans = "";
    String selected = "";
    int score = 0;
    int use = 9;
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnNe = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        lblQuizque = new javax.swing.JLabel();
        rdOpt4 = new javax.swing.JRadioButton();
        rdOpt1 = new javax.swing.JRadioButton();
        rdOpt2 = new javax.swing.JRadioButton();
        rdOpt3 = new javax.swing.JRadioButton();
        btnconfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNe.setBackground(new java.awt.Color(0, 102, 102));
        btnNe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNe.setForeground(new java.awt.Color(255, 255, 255));
        btnNe.setText("Next");
        btnNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeActionPerformed(evt);
            }
        });
        jPanel1.add(btnNe, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 90, 40));

        btnPre.setBackground(new java.awt.Color(0, 102, 102));
        btnPre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPre.setForeground(new java.awt.Color(255, 255, 255));
        btnPre.setText("Previous");
        jPanel1.add(btnPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 90, 40));

        lblQuizque.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblQuizque.setText("Question");
        jPanel1.add(lblQuizque, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 830, 40));

        rdOpt4.setBackground(new java.awt.Color(204, 204, 204));
        btngrp.add(rdOpt4);
        rdOpt4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        rdOpt4.setText("Option 4");
        rdOpt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOpt4ActionPerformed(evt);
            }
        });
        jPanel1.add(rdOpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 210, 40));

        rdOpt1.setBackground(new java.awt.Color(204, 204, 204));
        btngrp.add(rdOpt1);
        rdOpt1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        rdOpt1.setText("Option 1");
        jPanel1.add(rdOpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 40));

        rdOpt2.setBackground(new java.awt.Color(204, 204, 204));
        btngrp.add(rdOpt2);
        rdOpt2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        rdOpt2.setText("Option 2");
        rdOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOpt2ActionPerformed(evt);
            }
        });
        jPanel1.add(rdOpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 40));

        rdOpt3.setBackground(new java.awt.Color(204, 204, 204));
        btngrp.add(rdOpt3);
        rdOpt3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        rdOpt3.setText("Option 3");
        jPanel1.add(rdOpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 980, 480));

        btnconfirm.setBackground(new java.awt.Color(0, 102, 0));
        btnconfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("Submit");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOpt2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            data();
            
        } catch (SQLException ex) {
            Logger.getLogger(Exam_question.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void rdOpt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOpt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOpt4ActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btnNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeActionPerformed

        // TODO add your handling code here:
        
        
        if(rdOpt1.isSelected())
        {
            selected = rdOpt1.getText();
        }
        else if(rdOpt2.isSelected())
        {
            selected = rdOpt2.getText();
        }
         else if(rdOpt3.isSelected())
        {
            selected = rdOpt3.getText();
        }
         else if(rdOpt4.isSelected())
        {
            selected = rdOpt4.getText();
        }
         
         if(ans.equals(selected))
         {
             score = score +1;
             
         }
         
        use = use - 1;
        
       try{ data();}
       catch(SQLException e)
       {
       }   
    
    }//GEN-LAST:event_btnNeActionPerformed
    
    private void setQuestion()
    {
     for(int i = 1;i<10;i++)
     {
         q_no.add(i+1);
     }
     
     Collections.shuffle(q_no);
    }
    ArrayList questions;
        
    
    @SuppressWarnings("empty-statement")
    private void data() throws SQLException
    {
        if(use!=0){
        String query = "select * from questions where question_id = "+q_no.get(i);
        ResultSet rs = db.stm.executeQuery(query);
        while(rs.next())
        {
//            Object row[] = {rs.getString("questions")};
//            questions.add(row);
            lblQuizque.setText(rs.getString("Questions"));
            rdOpt1.setText(rs.getString("Option1"));
            rdOpt2.setText(rs.getString("Option2"));
            rdOpt3.setText(rs.getString("Option3"));
            rdOpt4.setText(rs.getString("Option4"));
            ans = rs.getString("Answer");
            
            i++;
            
            System.out.print("I :" + i + "    use = " + use);
            
        }
        }
        else
        {
            new score(Integer.toString(score)).setVisible(true);
            dispose();
        }
        btngrp.clearSelection();
    } 
    

    public String random()
    {
                Random rand = new Random(); 
        // Generate random integers in range 0 to 999 
        int rand_int1 = rand.nextInt(4);
        if(rand_int1 == 0)
        {
            return "A";
        }
        if(rand_int1 == 1){
            return "B";
        }
         if(rand_int1 == 2){
            return "C";
        }
         else{
            return "D";
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam_question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam_question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam_question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam_question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Exam_question().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Exam_question.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNe;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnconfirm;
    private javax.swing.ButtonGroup btngrp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuizque;
    private javax.swing.JRadioButton rdOpt1;
    private javax.swing.JRadioButton rdOpt2;
    private javax.swing.JRadioButton rdOpt3;
    private javax.swing.JRadioButton rdOpt4;
    // End of variables declaration//GEN-END:variables
}
